// Right-click menus: editor, text fields, canvas, graph.
import { _electron as electron } from 'playwright-core'
import { mkdtempSync, mkdirSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
const APP = process.env.APP_DIR, SHOT = process.env.SCREENSHOT_DIR || '/tmp/shots-menus'
mkdirSync(SHOT, { recursive: true })
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
let failed = 0
const check = (n, ok, d = '') => { if (!ok) failed++; console.log(`${ok ? 'PASS' : 'FAIL'}  ${n}${d ? '  — ' + d : ''}`) }
const app = await electron.launch({ executablePath: join(APP, 'node_modules/electron/dist/electron'), args: ['--no-sandbox', `--user-data-dir=${mkdtempSync(join(tmpdir(), 'nx-menu-'))}`, APP], cwd: APP, env: { ...process.env, NODE_ENV: 'production' }, timeout: 45000 })
const page = await app.firstWindow(); await page.waitForSelector('.nx-app'); await page.setViewportSize({ width: 1400, height: 900 })
const clip = () => app.evaluate(({ clipboard }) => clipboard.readText())
const setClip = (t) => app.evaluate(({ clipboard }, t) => clipboard.writeText(t), t)
const menuItems = () => page.evaluate(() => [...document.querySelectorAll('.nx-menu .nx-menu__item')].map((b) => (b.disabled ? '(' + b.textContent.trim() + ')' : b.textContent.trim())))
const pick = async (label) => { await page.locator('.nx-menu .nx-menu__item', { hasText: label }).first().click(); await sleep(400) }
const rclick = async (x, y) => { await page.mouse.click(x, y, { button: 'right' }); await sleep(300) }

const seeded = await page.evaluate(async () => {
  const t = (x) => [{ type: 'text', text: x, styles: {} }]; const u = () => crypto.randomUUID()
  const target = await window.api.pages.create(); await window.api.pages.update(target.id, { title: 'Target page' })
  const p = await window.api.pages.create()
  await window.api.pages.update(p.id, { title: 'Menus', content: JSON.stringify(['Alpha words here', 'Bravo words here', 'Charlie words here'].map((w) => ({ id: u(), type: 'paragraph', props: {}, content: t(w), children: [] }))) })
  const c = await window.api.canvases.create('Board')
  await window.api.canvases.update(c.id, { content: JSON.stringify({ version: 1, nodes: [
    { id: 'a', type: 'text', text: 'card a', x: 0, y: 0, width: 220, height: 110 },
    { id: 'b', type: 'text', text: 'card b', x: 320, y: 0, width: 220, height: 110 }],
    edges: [{ id: 'e1', fromNode: 'a', toNode: 'b', fromSide: 'right', toSide: 'left' }] }) })
  // linked pages so the graph has page nodes
  for (let i = 0; i < 4; i++) { const q = await window.api.pages.create(); await window.api.pages.update(q.id, { title: `G${i}`, content: JSON.stringify([{ id: u(), type: 'paragraph', props: {}, content: [{ type: 'pageMention', props: { pageId: target.id, pageTitle: 'x' } }], children: [] }]) }) }
  return { page: p.id, canvas: c.id }
})
await page.evaluate(() => window.location.reload()); await page.waitForSelector('.nx-app'); await sleep(800)

// ===== EDITOR =====
await page.evaluate((id) => window.nexus.store.getState().openPage(id), seeded.page)
await page.waitForSelector('.bn-editor'); await sleep(700)
const blocks = () => page.evaluate(() => [...document.querySelectorAll('.bn-block-content .bn-inline-content')].map((e) => e.textContent))
const word = page.locator('.bn-inline-content', { hasText: 'Bravo' }).first()
const wb0 = await word.boundingBox()
await page.mouse.dblclick(wb0.x + 12, wb0.y + wb0.height / 2); await sleep(200)
const wb = await page.evaluate(() => { const r = window.getSelection().getRangeAt(0).getBoundingClientRect(); return { x: r.x, y: r.y, width: r.width, height: r.height } })
await rclick(wb.x + wb.width / 2 - 15, wb.y + wb.height / 2)
const items = await menuItems()
await page.screenshot({ path: join(SHOT, 'editor-menu.png') })
check('right-click in the editor opens a menu', items.length >= 7, JSON.stringify(items))
await pick('Copy')
check('Copy from the menu copies the selected word', (await clip()).trim() === 'Bravo', JSON.stringify(await clip()))
await setClip('PASTED')
const ab = await page.locator('.bn-inline-content', { hasText: 'Alpha' }).first().boundingBox()
const cl = await page.locator('.bn-inline-content', { hasText: 'Charlie' }).first().boundingBox()
await page.mouse.click(cl.x + 5, cl.y + cl.height / 2); await sleep(300)
await page.mouse.click(ab.x + 5, ab.y + ab.height / 2); await page.keyboard.press('End'); await sleep(300)
await rclick(ab.x + 20, ab.y + ab.height / 2)
console.log('  paste menu:', JSON.stringify(await menuItems()), await page.evaluate(({ x, y }) => { const e = document.elementFromPoint(x, y); return e.className + ' ce=' + e.isContentEditable + ' inEditor=' + !!e.closest('.bn-editor') }, { x: ab.x + ab.width - 2, y: ab.y + ab.height / 2 }))
await pick('Paste')
check('Paste from the menu pastes the clipboard', (await blocks())[0].includes('PASTED'), JSON.stringify((await blocks())[0]))
const before = (await blocks()).length
const cb = await page.locator('.bn-inline-content', { hasText: 'Charlie' }).first().boundingBox()
await page.mouse.click(cb.x + 10, cb.y + cb.height / 2)
await rclick(cb.x + 10, cb.y + cb.height / 2); await pick('Duplicate block')
let after = await blocks()
check('Duplicate block adds a copy beneath it', after.length === before + 1 && after.filter((b) => b.startsWith('Charlie')).length === 2, JSON.stringify(after))
const cb2 = await page.locator('.bn-inline-content', { hasText: 'Charlie' }).last().boundingBox()
await page.mouse.click(cb2.x + 10, cb2.y + cb2.height / 2)
await rclick(cb2.x + 10, cb2.y + cb2.height / 2); await pick('Delete block')
after = await blocks()
check('Delete block removes it', after.filter((b) => b.startsWith('Charlie')).length === 1, JSON.stringify(after))
const cb3 = await page.locator('.bn-inline-content', { hasText: 'Charlie' }).first().boundingBox()
await page.mouse.click(cb3.x + cb3.width - 2, cb3.y + cb3.height / 2); await page.keyboard.press('End')
await rclick(cb3.x + cb3.width - 2, cb3.y + cb3.height / 2); await pick('Link to a page')
check('Link to a page opens the link menu at the cursor', await page.evaluate(() => !!document.querySelector('.nx-link-menu')))
await page.keyboard.press('Escape')

// ===== TEXT FIELD FALLBACK =====
await setClip('findme')
const search = page.locator('.nx-notes__list input').first()
const sb = await search.boundingBox()
await page.mouse.click(sb.x + 10, sb.y + sb.height / 2)
await rclick(sb.x + 10, sb.y + sb.height / 2)
const fItems = await menuItems()
check('right-click in an ordinary text field offers the edit menu', fItems.includes('Paste') && fItems.includes('(Cut)'), JSON.stringify(fItems))
await pick('Paste')
check('and Paste fills it', (await search.inputValue()) === 'findme', await search.inputValue())
await search.fill('')
await rclick(700, 860)
check('right-click on plain chrome opens nothing', (await menuItems()).length === 0)
await page.keyboard.press('Escape')

// ===== CANVAS =====
await page.evaluate((id) => window.nexus.store.getState().openCanvas(id), seeded.canvas)
await page.waitForSelector('.react-flow__node[data-id="a"]'); await sleep(900)
const stored = () => page.evaluate(async (id) => JSON.parse((await window.api.canvases.get(id)).content), seeded.canvas)
const box = (id) => page.evaluate((id) => { const r = document.querySelector(`.react-flow__node[data-id="${id}"]`).getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height } }, id)
const pane = await page.evaluate(() => { const r = document.querySelector('.react-flow__pane').getBoundingClientRect(); return { x: r.x + r.width - 220, y: r.y + r.height - 220 } })
await rclick(pane.x, pane.y)
const pItems = await menuItems()
await page.screenshot({ path: join(SHOT, 'canvas-pane-menu.png') })
check('right-click on empty canvas offers new cards here', pItems.includes('New text card here') && pItems.includes('New page card here…') && pItems.includes('Paste here'), JSON.stringify(pItems))
await pick('New text card here')
await page.keyboard.type('made by menu'); await page.keyboard.press('Escape'); await sleep(900)
let doc = await stored()
const made = doc.nodes.find((n) => n.text === 'made by menu')
check('it makes a text card', !!made)
const mb = made && await box(made.id)
check('centred where the click was', mb && Math.abs(mb.x + mb.w / 2 - pane.x) < 12 && Math.abs(mb.y + mb.h / 2 - pane.y) < 12, mb && `${(mb.x + mb.w / 2).toFixed(0)},${(mb.y + mb.h / 2).toFixed(0)} vs ${pane.x},${pane.y}`)
// card menu
await page.mouse.click(pane.x - 400, pane.y + 150); await sleep(200)
const ba = await box('a')
await rclick(ba.x + ba.w / 2, ba.y + ba.h / 2)
const cItems = await menuItems()
await page.screenshot({ path: join(SHOT, 'canvas-card-menu.png') })
check('right-click on a card selects it and offers its actions', cItems.join() === 'Edit,Make page,Copy,Cut,Duplicate,Delete' && await page.evaluate(() => document.querySelector('.react-flow__node[data-id="a"]').classList.contains('selected')), JSON.stringify(cItems))
await pick('Copy')
check('Copy puts the card\'s text on the clipboard', (await clip()) === 'card a', JSON.stringify(await clip()))
const n0 = (await stored()).nodes.length
await rclick(pane.x - 150, pane.y - 300); await pick('Paste here'); await sleep(700)
doc = await stored()
check('Paste here puts the copied card down', doc.nodes.length === n0 + 1 && doc.nodes.filter((n) => n.text === 'card a').length === 2)
await setClip('text from elsewhere')
await rclick(pane.x - 150, pane.y + 100); await pick('Paste here'); await sleep(700)
check('Paste here with text from another app makes a text card', (await stored()).nodes.some((n) => n.text === 'text from elsewhere'))
// duplicate / cut / delete via menu
await page.mouse.click(pane.x - 400, pane.y + 150); await sleep(200)
const bb = await box('b')
await rclick(bb.x + bb.w / 2, bb.y + bb.h / 2); await pick('Duplicate'); await sleep(700)
check('Duplicate makes a copy', (await stored()).nodes.filter((n) => n.text === 'card b').length === 2)
await page.mouse.click(pane.x - 400, pane.y + 150); await sleep(200)
await rclick(bb.x + 12, bb.y + 12); await pick('Cut'); await sleep(700)
check('Cut removes it and copies it', !(await stored()).nodes.some((n) => n.id === 'b') && (await clip()) === 'card b')
await page.keyboard.press('Control+z'); await sleep(700)
check('undo brings it back', (await stored()).nodes.some((n) => n.id === 'b'))
// edge
await sleep(300)
const ep = await page.evaluate(() => { const p = document.querySelector('.react-flow__edge[data-id="e1"] path.react-flow__edge-interaction, .react-flow__edge[data-id="e1"] path'); const l = p.getTotalLength(); const pt = p.getPointAtLength(l / 2); const m = p.getScreenCTM(); return { x: pt.x * m.a + m.e, y: pt.y * m.d + m.f } })
await rclick(ep.x, ep.y)
const eItems = await menuItems()
check('right-click on an arrow offers label, line and delete', eItems.join() === 'Label,Make it a line,Delete', JSON.stringify(eItems))
await pick('Make it a line'); await sleep(700)
check('Make it a line takes the arrowhead off', (await stored()).edges.find((e) => e.id === 'e1')?.toEnd === 'none')
// multi-select delete
await page.mouse.click(pane.x - 400, pane.y + 150); await sleep(200)
const ba2 = await box('a'); const bb2 = await box('b')
await page.mouse.click(ba2.x + 20, ba2.y + 20)
await page.keyboard.down('Control'); await page.mouse.click(bb2.x + 20, bb2.y + 20); await page.keyboard.up('Control'); await sleep(200)
await rclick(bb2.x + 30, bb2.y + 30)
const mItems = await menuItems()
check('right-click inside a selection of two acts on both', mItems.join() === 'Copy,Cut,Duplicate,Delete', JSON.stringify(mItems))
await pick('Delete'); await sleep(700)
doc = await stored()
check('and Delete removes both', !doc.nodes.some((n) => n.id === 'a' || n.id === 'b'))
// page card via picker at spot
await rclick(pane.x - 300, pane.y - 200); await pick('New page card here…')
check('New page card here opens the page picker', await page.evaluate(() => !!document.querySelector('.nx-canvas-picker, [class*=picker] input')))
await page.keyboard.type('Target'); await sleep(400); await page.keyboard.press('Enter'); await sleep(900)
doc = await stored()
const pc = doc.nodes.find((n) => n.type === 'page')
const pcb = pc && await box(pc.id)
check('and the page card lands where the right-click was', pcb && Math.abs(pcb.x + pcb.w / 2 - (pane.x - 300)) < 12, pcb && `${(pcb.x + pcb.w / 2).toFixed(0)} vs ${pane.x - 300}`)

// ===== GRAPH =====
await page.evaluate(() => window.nexus.store.getState().setActiveView('home'))
await page.waitForSelector('.nx-graph__node--page'); await sleep(5000)
await page.evaluate(() => document.querySelector('.nx-graph__canvas').scrollIntoView({ block: 'center' })); await sleep(300)
const gn = await page.evaluate(() => { const n = document.querySelectorAll('.nx-graph__node--page')[1]; const r = n.querySelector('.nx-graph__node-dot').getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 } })
await page.mouse.move(gn.x, gn.y); await sleep(200)
await rclick(gn.x, gn.y)
const gItems = await menuItems()
check('right-click on a graph node offers Open and Pin', gItems.join() === 'Open page,Pin here', JSON.stringify(gItems))
await pick('Pin here')
check('Pin here pins it', await page.evaluate(({ x, y }) => !!document.elementFromPoint(x, y)?.closest('.nx-graph__node--pinned'), gn))
await rclick(gn.x, gn.y)
check('and the menu then offers Unpin', (await menuItems()).includes('Unpin'))
await page.keyboard.press('Escape')
const gbg = await page.evaluate(() => { const r = document.querySelector('.nx-graph__canvas').getBoundingClientRect(); return { x: r.x + r.width * 0.06, y: r.y + r.height * 0.55 } })
await rclick(gbg.x, gbg.y)
check('right-click on the graph background offers Fit and Unpin all', (await menuItems()).join() === 'Fit graph to view,Unpin all', JSON.stringify(await menuItems()))
await page.keyboard.press('Escape')

await app.close()
console.log(failed ? `\n${failed} FAILED` : '\nALL PASS'); process.exit(failed ? 1 : 0)
